---
- project:
    name: packit-service/packit-service
    check:
      jobs:
 #       - packit-service-pre-commit
        - packit-service-tests
    gate:
      jobs:
        - packit-service-pre-commit
        - packit-service-tests

- job:
    name: packit-service-pre-commit
    parent: base
    description: Check precommit
    run: files/zuul-pre-commit.yaml
    extra-vars:
      ansible_python_interpreter: /usr/bin/python3
    nodeset:
      nodes:
        - name: test-node
          label: cloud-fedora-30

- job:
    name: packit-service-tests
    parent: base
    description: Run tests of packit via rpms
    required-projects:
      - github.com/packit-service/deployment
    pre-run:
      - files/install-openshift.yaml
      - files/packit-service-image.yaml
      - files/deployment.yaml
    run: files/zuul-tests.yaml
    extra-vars:
      with_testing: true
      ansible_python_interpreter: /usr/bin/python3
    nodeset:
      nodes:
        - name: test-node
          label: cloud-fedora-30
