---
- name: Deploy source-git
  hosts: all
  become: true
  tasks:
  - name: Gracefully remove syncer and watcher
    command: podman rm -f watcher syncer
    ignore_errors: true
  - name: Run watcher locally
    command: podman run -d --name watcher \
              -e GITHUB_TOKEN={{ github_token }} \
              -e PAGURE_PACKAGE_TOKEN={{ pagure_package_token }} \
              -e PAGURE_USER_TOKEN={{ pagure_user_token }} \
              -e PAGURE_FORK_TOKEN={{ pagure_fork_token }} \
              -e PYTHONPATH=/src \
              -v {{ playbook_dir }}:/src:Z \
              -w /src \
              {{ source_git_image }} \
              sourcegit -d watch-fedora-ci
  - name: Run syncer locally
    command: podman run -d --name syncer \
              -e PAGURE_PACKAGE_TOKEN={{ pagure_package_token }} \
              -e PAGURE_USER_TOKEN={{ pagure_user_token }} \
              -e PAGURE_FORK_TOKEN={{ pagure_fork_token }} \
              -e PYTHONPATH=/src \
              -v {{ playbook_dir }}:/src:Z \
              -w /src \
              {{ source_git_image }} \
              sourcegit -d watch-pr --updated
