version: "2"

services:

  redis:
    image: registry.fedoraproject.org/f28/redis
    container_name: redis
    ports:
      - 6379:6379
    user: "123123"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - 8081:8081
    user: "123123"

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - 5555:5555
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    user: "123123"

  packit-worker:
    container_name: packit-worker
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/usercont/packit-service:master
    command: /usr/bin/run_worker.sh
    depends_on:
      - redis
    environment:
      REDIS_SERVICE_HOST: redis
      APP: packit_service.worker.tasks
    user: "123123"

  packit-service:
    container_name: packit-service
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/usercont/packit-service:master
    #command: /usr/bin/run-httpd  # TODO: make this work instead of the below flask
    command: flask-3 run -h 0.0.0.0 -p 8443
    depends_on:
      - redis
    ports:
      - 8443:8443
    environment:
      REDIS_SERVICE_HOST: redis
      FLASK_ENV: development
      FLASK_APP: packit_service.service.web_hook
    volumes:
      - ./packit_service:/usr/local/lib/python3.7/site-packages/packit_service:ro,z
      # There's no secrets/ by default. You have to create (or symlink to other dir) it yourself.
      - ./secrets/httpd-packit.conf:/etc/httpd/conf.d/httpd-packit.conf:ro,Z
      - ./secrets/id_rsa:/opt/app-root/src/.ssh/id_rsa:ro,z
      - ./secrets/id_rsa.pub:/opt/app-root/src/.ssh/id_rsa.pub:ro,z
      - ./secrets/packit.yaml:/opt/app-root/src/.config/.packit.yaml:ro,z
      - ./secrets/copr:/opt/app-root/src/.config/copr:ro,Z
      - ./secrets/fedora.keytab:/secrets/fedora.keytab:ro,Z
      - ./secrets/private-key.pem:/secrets/private-key.pem:ro,Z
      - ./secrets/fullchain.pem:/secrets/fullchain.pem:ro,Z
      - ./secrets/privkey.pem:/secrets/privkey.pem:ro,Z
    #user: "123123"

  packit-fedmsg:
    container_name: packit-fedmsg-listener
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/usercont/packit-service:master
    command: packit-service --debug listen-to-fedmsg
    depends_on:
      - redis
    environment:
      REDIS_SERVICE_HOST: redis
    volumes:
      - ./packit_service:/usr/local/lib/python3.7/site-packages/packit_service:ro,z
      # There's no secrets/ by default. You have to create (or symlink to other dir) it yourself.
      - ./secrets/id_rsa:/opt/app-root/src/.ssh/id_rsa:ro,z
      - ./secrets/id_rsa.pub:/opt/app-root/src/.ssh/id_rsa.pub:ro,z
      - ./secrets/packit.yaml:/opt/app-root/src/.config/.packit.yaml:ro,z
    #user: "123123"
